# Generated by Django 4.2.1 on 2023-06-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="last_gift_selection_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
