# Generated by Django 4.2.1 on 2024-03-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_userprofile_last_gift_selection_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Letters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
            ],
        ),
    ]
